[package]
name = "the_pink_sand_simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
rand = "0.9.0"

[dev-dependencies]
criterion = "0.8"

[[bench]]
name = "main_benchmark"
harness = false
